#!/usr/bin/env python3
"""Pure safety helpers for official TARE goal validation.

This module deliberately contains no exploration scoring, room state,
corridor bias, doorway synthesis, frontier selection, or return behavior.
"""

import math
from dataclasses import dataclass


def _distance(first, second):
    return math.hypot(
        float(first[0]) - float(second[0]),
        float(first[1]) - float(second[1]))


@dataclass
class TareGoalSafetyConfig:
    goal_clearance: float = 0.32
    local_shift_max: float = 0.75
    local_shift_step: float = 0.15
    tare_path_max_age: float = 3.0
    candidate_min_robot_distance: float = 0.35
    candidate_max_original_distance: float = 4.0


def goal_is_observed_free(grid, point, clearance):
    """Require an observed-free endpoint and body-radius clearance."""
    cell = grid.world_to_cell(point)
    if cell is None:
        return False
    radius_cells = max(1, int(math.ceil(clearance / grid.resolution)))
    for dy in range(-radius_cells, radius_cells + 1):
        for dx in range(-radius_cells, radius_cells + 1):
            if math.hypot(dx, dy) * grid.resolution > clearance:
                continue
            x, y = cell[0] + dx, cell[1] + dy
            if (not 0 <= x < grid.width or not 0 <= y < grid.height or
                    int(grid.data[y, x]) != 0):
                return False
    return True


def goal_has_no_known_collision(grid, point, clearance):
    """Accept free/unknown clearance, but reject known occupied or off-map.

    An Official TARE exploration viewpoint can legitimately lie just beyond
    the currently observed free-space boundary.  Treating every unknown cell
    as a collision prevents the robot from ever crossing that boundary.  This
    predicate is intentionally only a known-obstacle check; SCAN-lite and the
    downstream FAR/A* stage still validate reachability and the executable
    local path.
    """
    cell = grid.world_to_cell(point)
    if cell is None:
        return False
    radius_cells = max(1, int(math.ceil(clearance / grid.resolution)))
    for dy in range(-radius_cells, radius_cells + 1):
        for dx in range(-radius_cells, radius_cells + 1):
            if math.hypot(dx, dy) * grid.resolution > clearance:
                continue
            x, y = cell[0] + dx, cell[1] + dy
            if not 0 <= x < grid.width or not 0 <= y < grid.height:
                return False
            if int(grid.data[y, x]) > 0:
                return False
    return True


def _repair_offsets(config):
    """Return deterministic nearest-first offsets around the TARE endpoint."""
    step = max(0.05, float(config.local_shift_step))
    maximum = max(0.0, float(config.local_shift_max))
    offsets = []
    ring = step
    while ring <= maximum + 1e-9:
        samples = max(8, int(math.ceil(2.0 * math.pi * ring / step)))
        for index in range(samples):
            angle = 2.0 * math.pi * index / samples
            offsets.append((ring * math.cos(angle),
                            ring * math.sin(angle)))
        ring += step
    return offsets


def locally_shift_goal_to_free_space(grid, robot_pose, tare_goal, config,
                                     validator=None):
    """Repair only the endpoint locally; preserve TARE's target neighborhood."""
    goal = tuple(float(value) for value in tare_goal[:3])
    robot = tuple(float(value) for value in robot_pose[:3])
    heading = math.atan2(goal[1] - robot[1], goal[0] - robot[0])
    along = math.cos(heading), math.sin(heading)
    side = -along[1], along[0]
    candidates = []
    for dx, dy in _repair_offsets(config):
        point = (goal[0] + dx, goal[1] + dy, goal[2])
        if not goal_is_observed_free(grid, point, config.goal_clearance):
            continue
        if validator is not None and not validator(point):
            continue
        # Prefer the smallest change.  For equal shifts, prefer motion along
        # the original robot-to-TARE ray over a lateral semantic change.
        longitudinal = dx * along[0] + dy * along[1]
        lateral = abs(dx * side[0] + dy * side[1])
        candidates.append((math.hypot(dx, dy), lateral,
                           abs(longitudinal), point))
    if not candidates:
        return None
    return min(candidates, key=lambda item: item[:3])[3]


def candidate_from_tare_path(grid, robot_pose, tare_goal, tare_path, config,
                             validator=None):
    """Select only from poses generated by Official TARE's exploration path."""
    robot = tuple(float(value) for value in robot_pose[:3])
    goal = tuple(float(value) for value in tare_goal[:3])
    candidates = []
    for index, raw in enumerate(tare_path or []):
        if len(raw) < 2:
            continue
        point = (float(raw[0]), float(raw[1]),
                 float(raw[2]) if len(raw) > 2 else goal[2])
        robot_distance = _distance(robot, point)
        original_distance = _distance(goal, point)
        if (robot_distance < config.candidate_min_robot_distance or
                original_distance >
                config.candidate_max_original_distance):
            continue
        if not goal_is_observed_free(grid, point, config.goal_clearance):
            continue
        candidates.append((original_distance, -robot_distance, index, point))
    # Test reachability nearest to TARE's requested endpoint first.  Running
    # an A* validator for every path vertex is unnecessarily expensive and can
    # block the 1 Hz goal filter on long Official TARE tours.
    candidates.sort(key=lambda item: item[:3])
    for candidate in candidates:
        point = candidate[3]
        if validator is None or validator(point):
            return point
    return None
