DWAPlannerROS:
  odom_topic: /state_estimation
  max_vel_x: 2.0
  min_vel_x: 0.0
  max_vel_trans: 2.0
  min_vel_trans: 0.05
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 1.00
  min_vel_theta: 0.20
  acc_lim_x: 0.70
  acc_lim_y: 0.0
  acc_lim_theta: 2.00
  holonomic_robot: false

  xy_goal_tolerance: 0.35
  yaw_goal_tolerance: 0.25
  latch_xy_goal_tolerance: true

  sim_time: 1.5
  sim_granularity: 0.05
  angular_sim_granularity: 0.05
  vx_samples: 16
  vy_samples: 1
  vtheta_samples: 24
  path_distance_bias: 36.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05
  forward_point_distance: 0.45
  stop_time_buffer: 0.25
  scaling_speed: 0.6
  max_scaling_factor: 0.2
  oscillation_reset_dist: 0.20
  prune_plan: true
  publish_traj_pc: false
  publish_cost_grid_pc: false
